const {test}=require('node:test');
const assert=require('node:assert/strict');
const E=require('../js/tools/mix-engine.js');
const fixture=(r={})=>({...E.plan(),client:'QA',date:'2026-09-07',start:'2026-09-01',end:'2026-09-30',budget:1100000,rows:[{...E.row(),amount:1100000,markup:10,rate:100,ctr:2,cvr:1,aov:50000,source:'QA fixture',approved:true,...r}]});
test('markup removed before forecast; advertiser ROAS uses invoice supply',()=>{const x=E.compute(fixture());assert.equal(x.errors.length,0);assert.ok(Math.abs(x.rows[0].media-1000000)<1e-8);assert.ok(Math.abs(x.rows[0].clicks-10000)<1e-8);assert.equal(Math.round(x.rows[0].conv),100);assert.equal(Math.round(x.rows[0].revenue),5000000);assert.equal(x.totals.gross,1210000);});
test('zero CVR retained, not missing/default',()=>{const x=E.compute(fixture({cvr:0}));assert.equal(x.rows[0].conv,0);assert.equal(x.rows[0].revenue,0);assert.equal(x.rows[0].roas,0);assert.equal(x.rows[0].cpa,null);});
test('unknown CVR does not turn into zero conversion',()=>assert.equal(E.compute(fixture({cvr:''})).totals.conv,null));
test('allocation reconciles integer won, preserves fixed budgets',()=>{const p=fixture();p.budget=100;p.rows=[{...E.row(),amount:1,locked:true},...Array.from({length:7},()=>E.row())];E.allocate(p);assert.equal(p.rows.reduce((s,r)=>s+r.amount,0),100);assert.equal(p.rows[0].amount,1);});
test('fixed budget over total fails closed',()=>assert.throws(()=>E.allocate({...fixture(),budget:10,rows:[{...E.row(),locked:true,amount:11}]})));
test('VAT inclusive conversion and zero tax',()=>{let p=fixture();p.vatMode='in';p.budget=1210000;assert.equal(E.compute(p).expected,1100000);p.tax=0;p.budget=1100000;assert.equal(E.compute(p).totals.gross,1100000);});
test('CPC and CPM consistent funnel',()=>{const x=E.compute(fixture({model:'CPM',rate:2000}));assert.equal(Math.round(x.rows[0].impr),500000);assert.equal(Math.round(x.rows[0].clicks),10000);});
test('CPV independent video metrics',()=>{const x=E.compute(fixture({model:'CPV',rate:20,vtr:25}));assert.equal(Math.round(x.rows[0].views),50000);assert.equal(Math.round(x.rows[0].impr),200000);});
test('message sends never become clicks or conversions',()=>{const x=E.compute(fixture({model:'SEND',rate:20,goal:'기타'}));assert.equal(Math.round(x.rows[0].sends),50000);assert.equal(x.rows[0].clicks,null);assert.equal(x.rows[0].conv,null);});
test('prepaid fixed zero budget can retain independent volume',()=>{const x=E.compute(fixture({model:'FIXED',amount:0,fixedClicks:1000,fixedImpr:10000}));assert.equal(x.rows[0].clicks,1000);assert.equal(x.rows[0].roas,null);});
test('CPI conversions are installations, not purchases',()=>{const p=fixture({model:'CPI',rate:1000,goal:'설치'});const x=E.compute(p);assert.equal(Math.round(x.rows[0].conv),1000);assert.equal(x.rows[0].revenue,null);p.rows[0].goal='구매';assert.ok(E.compute(p).errors.some(x=>x.includes('설치')));});
test('unmeasured totals suppressed, mixed conversion types not summed',()=>{const p=fixture();p.rows.push({...p.rows[0],goal:'리드',cvr:''});const x=E.compute(p);assert.equal(x.totals.conv,null);assert.equal(x.totals.revenue,null);});
test('calendar inclusive days and invalid dates',()=>{assert.equal(E.days('2026-09-01','2026-09-30'),30);assert.equal(E.days('2026-02-30','2026-03-01'),null);assert.equal(E.days('2026-09-30','2026-09-01'),null);});
test('strict numeric parser rejects trailing junk',()=>{assert.equal(E.num('1,000'),1000);assert.equal(E.num('100원'),null);assert.equal(E.num('Infinity'),null);assert.equal(E.num(''),null);});
test('invalid percentages and export approval block',()=>{const x=E.compute(fixture({ctr:101,approved:false}));assert.ok(x.errors.some(x=>x.includes('CTR')));assert.ok(x.errors.some(x=>x.includes('검토')));});
test('conservative unit-cost scenario reduces clicks',()=>{const p=fixture();p.scenario=120;assert.ok(Math.abs(E.compute(p).rows[0].clicks-10000/1.2)<1e-8);});
test('pack duplicate id rejected',()=>{const r={id:'x',brand:'x',source:'x',product:'naver-search'};assert.throws(()=>E.validatePack({version:1,benchmarks:[r,r]}));});
